#include "mainwindow.h"
#include "amigaguide/document_editor.h"
#include "amigaguide/parser.h"
#include <algorithm>
#include <QAction>
#include <QCheckBox>
#include <QDialog>
#include <QDialogButtonBox>
#include <QFile>
#include <QFileDialog>
#include <QFileInfo>
#include <QFormLayout>
#include <QGroupBox>
#include <QInputDialog>
#include <QLabel>
#include <QLineEdit>
#include <QListWidget>
#include <QMenuBar>
#include <QMessageBox>
#include <QPlainTextEdit>
#include <QScrollArea>
#include <QSpinBox>
#include <QSplitter>
#include <QStatusBar>
#include <QTextCursor>
#include <QVBoxLayout>

namespace {
amigaguide::NodeProperty propertyFor(QObject* o){const auto n=o->objectName();if(n=="keywords")return amigaguide::NodeProperty::Keywords;if(n=="prev")return amigaguide::NodeProperty::Prev;if(n=="next")return amigaguide::NodeProperty::Next;if(n=="help")return amigaguide::NodeProperty::Help;if(n=="toc")return amigaguide::NodeProperty::Toc;if(n=="index")return amigaguide::NodeProperty::Index;if(n=="font")return amigaguide::NodeProperty::Font;return amigaguide::NodeProperty::TabWidth;}
amigaguide::NodeFlag flagFor(QObject* o){const auto n=o->objectName();if(n=="smartwrap")return amigaguide::NodeFlag::SmartWrap;if(n=="proportional")return amigaguide::NodeFlag::Proportional;return amigaguide::NodeFlag::WordWrap;}
}

MainWindow::MainWindow(QWidget* parent):QMainWindow(parent){
    setWindowTitle("AmigaGuide Editor");resize(1100,700);
    auto* splitter=new QSplitter(this);auto* left=new QWidget(splitter);auto* leftLayout=new QVBoxLayout(left);leftLayout->addWidget(new QLabel("Nodes",left));nodes_=new QListWidget(left);leftLayout->addWidget(nodes_);
    auto* right=new QWidget(splitter);auto* rightLayout=new QVBoxLayout(right);auto* props=new QGroupBox("Node Properties",right);auto* form=new QFormLayout(props);
    titleEdit_=new QLineEdit(props);titleEdit_->setPlaceholderText("Node title");form->addRow("Title",titleEdit_);
    auto addText=[&](QLineEdit*& e,const char* name,const QString& label){e=new QLineEdit(props);e->setObjectName(name);form->addRow(label,e);connect(e,&QLineEdit::editingFinished,this,&MainWindow::propertyEdited);};
    addText(keywordsEdit_,"keywords","Keywords");addText(prevEdit_,"prev","Prev");addText(nextEdit_,"next","Next");addText(helpEdit_,"help","Help");addText(tocEdit_,"toc","TOC");addText(indexEdit_,"index","Index");addText(fontEdit_,"font","Font");
    tabWidthEdit_=new QSpinBox(props);tabWidthEdit_->setRange(0,1000);tabWidthEdit_->setSpecialValueText("Default");form->addRow("Tab width",tabWidthEdit_);connect(tabWidthEdit_,&QSpinBox::editingFinished,this,&MainWindow::propertyEdited);
    wordWrapEdit_=new QCheckBox("Word wrap",props);wordWrapEdit_->setObjectName("wordwrap");smartWrapEdit_=new QCheckBox("Smart wrap",props);smartWrapEdit_->setObjectName("smartwrap");proportionalEdit_=new QCheckBox("Proportional",props);proportionalEdit_->setObjectName("proportional");
    form->addRow("Options",wordWrapEdit_);form->addRow("",smartWrapEdit_);form->addRow("",proportionalEdit_);connect(wordWrapEdit_,&QCheckBox::toggled,this,&MainWindow::flagEdited);connect(smartWrapEdit_,&QCheckBox::toggled,this,&MainWindow::flagEdited);connect(proportionalEdit_,&QCheckBox::toggled,this,&MainWindow::flagEdited);
    auto* scroll=new QScrollArea(right);scroll->setWidget(props);scroll->setWidgetResizable(true);scroll->setMaximumHeight(250);rightLayout->addWidget(scroll);editor_=new QPlainTextEdit(right);editor_->setLineWrapMode(QPlainTextEdit::NoWrap);rightLayout->addWidget(editor_,1);
    splitter->addWidget(left);splitter->addWidget(right);splitter->setStretchFactor(1,1);splitter->setSizes({300,800});setCentralWidget(splitter);
    auto* fileMenu=menuBar()->addMenu("&File");auto* a=new QAction("&New",this);a->setShortcut(QKeySequence::New);connect(a,&QAction::triggered,this,&MainWindow::newFile);fileMenu->addAction(a);a=new QAction("&Open...",this);a->setShortcut(QKeySequence::Open);connect(a,&QAction::triggered,this,&MainWindow::open);fileMenu->addAction(a);a=new QAction("&Save",this);a->setShortcut(QKeySequence::Save);connect(a,&QAction::triggered,this,&MainWindow::save);fileMenu->addAction(a);a=new QAction("Save &As...",this);a->setShortcut(QKeySequence::SaveAs);connect(a,&QAction::triggered,this,&MainWindow::saveAs);fileMenu->addAction(a);a=new QAction("Document &Properties...",this);connect(a,&QAction::triggered,this,&MainWindow::documentProperties);fileMenu->addAction(a);fileMenu->addSeparator();a=new QAction("E&xit",this);a->setShortcut(QKeySequence::Quit);connect(a,&QAction::triggered,this,&QWidget::close);fileMenu->addAction(a);
    auto* editMenu=menuBar()->addMenu("&Edit");a=new QAction("&Undo",this);a->setShortcut(QKeySequence::Undo);connect(a,&QAction::triggered,editor_,&QPlainTextEdit::undo);connect(editor_,&QPlainTextEdit::undoAvailable,a,&QAction::setEnabled);a->setEnabled(false);editMenu->addAction(a);a=new QAction("&Redo",this);a->setShortcut(QKeySequence::Redo);connect(a,&QAction::triggered,editor_,&QPlainTextEdit::redo);connect(editor_,&QPlainTextEdit::redoAvailable,a,&QAction::setEnabled);a->setEnabled(false);editMenu->addAction(a);editMenu->addSeparator();a=new QAction("&Cut",this);a->setShortcut(QKeySequence::Cut);connect(a,&QAction::triggered,editor_,&QPlainTextEdit::cut);editMenu->addAction(a);a=new QAction("&Copy",this);a->setShortcut(QKeySequence::Copy);connect(a,&QAction::triggered,editor_,&QPlainTextEdit::copy);editMenu->addAction(a);a=new QAction("&Paste",this);a->setShortcut(QKeySequence::Paste);connect(a,&QAction::triggered,editor_,&QPlainTextEdit::paste);editMenu->addAction(a);
    auto* nodeMenu=menuBar()->addMenu("&Node");a=new QAction("&New Node...",this);a->setShortcut(QKeySequence(Qt::CTRL|Qt::SHIFT|Qt::Key_N));connect(a,&QAction::triggered,this,&MainWindow::newNode);nodeMenu->addAction(a);a=new QAction("&Rename Node...",this);connect(a,&QAction::triggered,this,&MainWindow::renameNode);nodeMenu->addAction(a);a=new QAction("&Delete Node",this);a->setShortcut(QKeySequence::Delete);connect(a,&QAction::triggered,this,&MainWindow::deleteNode);nodeMenu->addAction(a);
    connect(editor_,&QPlainTextEdit::textChanged,this,&MainWindow::updateNodes);connect(nodes_,&QListWidget::currentRowChanged,this,&MainWindow::nodeActivated);connect(titleEdit_,&QLineEdit::editingFinished,this,&MainWindow::titleEdited);statusBar()->showMessage("Ready");newFile();
}
void MainWindow::newFile(){if(!maybeSave())return;updating_=true;editor_->setPlainText("@database New AmigaGuide\n\n@node Main\n@title Main\n\n@endnode\n");updating_=false;filePath_.clear();setWindowTitle("AmigaGuide Editor — Untitled");updateNodes();editor_->document()->setModified(false);}
void MainWindow::open(){const QString p=QFileDialog::getOpenFileName(this,"Open AmigaGuide",{},"AmigaGuide (*.guide *.amigaguide);;All files (*)");if(!p.isEmpty())openFile(p);}
void MainWindow::openFile(const QString& p){if(!maybeSave())return;QFile f(p);if(!f.open(QIODevice::ReadOnly|QIODevice::Text)){QMessageBox::warning(this,"Open failed","Could not open the selected AmigaGuide file.");return;}loadSource(QString::fromUtf8(f.readAll()));setDocumentPath(p);statusBar()->showMessage("Opened "+QFileInfo(p).fileName());}
void MainWindow::loadSource(const QString& s){updating_=true;editor_->setPlainText(s);updating_=false;updateNodes();editor_->document()->setModified(false);}
void MainWindow::save(){if(filePath_.isEmpty())saveAs();else saveTo(filePath_);}
void MainWindow::saveAs(){const QString p=QFileDialog::getSaveFileName(this,"Save AmigaGuide",filePath_.isEmpty()?"untitled.guide":filePath_,"AmigaGuide (*.guide);;All files (*)");if(!p.isEmpty())saveTo(p);}
bool MainWindow::saveTo(const QString& p){QFile f(p);if(!f.open(QIODevice::WriteOnly|QIODevice::Text)){QMessageBox::warning(this,"Save failed","Could not save the AmigaGuide file.");return false;}f.write(editor_->toPlainText().toUtf8());setDocumentPath(p);editor_->document()->setModified(false);statusBar()->showMessage("Saved "+QFileInfo(p).fileName());return true;}
void MainWindow::setDocumentPath(const QString& p){filePath_=p;setWindowTitle((QFileInfo(p).fileName().isEmpty()?"Untitled":QFileInfo(p).fileName())+" — AmigaGuide Editor");}
void MainWindow::updateNodes(){if(updating_)return;const QString selected=nodes_->currentItem()?nodes_->currentItem()->text():QString{};const int old=nodes_->currentRow();const std::string source=editor_->toPlainText().toUtf8().toStdString();amigaguide::Document d;amigaguide::ParseError e;if(!amigaguide::Parser{}.parse(source,d,&e)){nodes_->clear();refreshProperties(-1);statusBar()->showMessage(QString("Parse error on line %1: %2").arg(e.line).arg(QString::fromStdString(e.message)));return;}updating_=true;nodes_->clear();int row=-1;for(std::size_t i=0;i<d.nodes().size();++i){nodes_->addItem(QString::fromStdString(d.nodes()[i].name));if(!selected.isEmpty()&&selected==QString::fromStdString(d.nodes()[i].name))row=static_cast<int>(i);}if(row<0&&old>=0&&old<nodes_->count())row=old;if(row>=0)nodes_->setCurrentRow(row);updating_=false;nodeActivated(nodes_->currentRow());statusBar()->showMessage(QString("%1 node(s)").arg(d.nodes().size()));}
void MainWindow::nodeActivated(int row){if(row<0){refreshProperties(-1);return;}const std::string source=editor_->toPlainText().toUtf8().toStdString();amigaguide::Document d;if(!amigaguide::Parser{}.parse(source,d)||row>=static_cast<int>(d.nodes().size()))return;refreshProperties(row);const auto& n=d.nodes()[static_cast<std::size_t>(row)];const qsizetype start=QString::fromUtf8(source.data(),static_cast<qsizetype>(n.source_begin)).size();const qsizetype end=QString::fromUtf8(source.data(),static_cast<qsizetype>(n.source_end)).size();QTextCursor c=editor_->textCursor();c.setPosition(start);c.setPosition(end,QTextCursor::KeepAnchor);editor_->setTextCursor(c);editor_->centerCursor();}
void MainWindow::refreshProperties(int row){updating_=true;const std::string source=editor_->toPlainText().toUtf8().toStdString();amigaguide::Document d;if(row>=0&&amigaguide::Parser{}.parse(source,d)&&row<static_cast<int>(d.nodes().size())){const auto& n=d.nodes()[static_cast<std::size_t>(row)];titleEdit_->setText(QString::fromStdString(n.title));keywordsEdit_->setText(QString::fromStdString(n.keywords));prevEdit_->setText(QString::fromStdString(n.prev));nextEdit_->setText(QString::fromStdString(n.next));helpEdit_->setText(QString::fromStdString(n.help));tocEdit_->setText(QString::fromStdString(n.toc));indexEdit_->setText(QString::fromStdString(n.index));fontEdit_->setText(QString::fromStdString(n.font));tabWidthEdit_->setValue(n.tab_width);wordWrapEdit_->setChecked(n.word_wrap);smartWrapEdit_->setChecked(n.smart_wrap);proportionalEdit_->setChecked(n.proportional);titleEdit_->setEnabled(true);keywordsEdit_->setEnabled(true);prevEdit_->setEnabled(true);nextEdit_->setEnabled(true);helpEdit_->setEnabled(true);tocEdit_->setEnabled(true);indexEdit_->setEnabled(true);fontEdit_->setEnabled(true);tabWidthEdit_->setEnabled(true);wordWrapEdit_->setEnabled(true);smartWrapEdit_->setEnabled(true);proportionalEdit_->setEnabled(true);}else{titleEdit_->clear();keywordsEdit_->clear();prevEdit_->clear();nextEdit_->clear();helpEdit_->clear();tocEdit_->clear();indexEdit_->clear();fontEdit_->clear();tabWidthEdit_->setValue(0);wordWrapEdit_->setChecked(false);smartWrapEdit_->setChecked(false);proportionalEdit_->setChecked(false);titleEdit_->setEnabled(false);keywordsEdit_->setEnabled(false);prevEdit_->setEnabled(false);nextEdit_->setEnabled(false);helpEdit_->setEnabled(false);tocEdit_->setEnabled(false);indexEdit_->setEnabled(false);fontEdit_->setEnabled(false);tabWidthEdit_->setEnabled(false);wordWrapEdit_->setEnabled(false);smartWrapEdit_->setEnabled(false);proportionalEdit_->setEnabled(false);}updating_=false;}
void MainWindow::setNodeSelection(int row){if(row>=0&&row<nodes_->count())nodes_->setCurrentRow(row);}
bool MainWindow::applyNodeEdit(const QString& op,int row){const std::string s=editor_->toPlainText().toUtf8().toStdString();amigaguide::Document d;amigaguide::ParseError e;if(!amigaguide::Parser{}.parse(s,d,&e)){QMessageBox::warning(this,"Cannot edit node",QString("The document must parse before a node can be %1.").arg(op));return false;}return row>=0&&row<static_cast<int>(d.nodes().size());}
void MainWindow::replaceSource(const std::string& s,int row,const QString& msg){updating_=true;editor_->setPlainText(QString::fromUtf8(s.data(),static_cast<qsizetype>(s.size())));updating_=false;editor_->document()->setModified(true);updateNodes();setNodeSelection(row);statusBar()->showMessage(msg);}
void MainWindow::newNode(){bool ok=false;const QString name=QInputDialog::getText(this,"New Node","Node name:",QLineEdit::Normal,"NewNode",&ok);if(!ok)return;const QString title=QInputDialog::getText(this,"New Node","Node title:",QLineEdit::Normal,name,&ok);if(!ok)return;amigaguide::Document d;amigaguide::ParseError e;if(!amigaguide::Parser{}.parse(editor_->toPlainText().toUtf8().toStdString(),d,&e)){QMessageBox::warning(this,"Cannot add node","Fix the document's parse errors before adding a node.");return;}amigaguide::DocumentEditor edit(d);std::string err;if(!edit.add_node(name.toUtf8().toStdString(),title.toUtf8().toStdString(),&err)){QMessageBox::warning(this,"Cannot add node",QString::fromStdString(err));return;}replaceSource(d.source(),static_cast<int>(d.nodes().size())-1,"Added node "+name);}
void MainWindow::renameNode(){const int row=nodes_->currentRow();if(!applyNodeEdit("rename",row))return;const QString current=nodes_->currentItem()->text();bool ok=false;const QString name=QInputDialog::getText(this,"Rename Node","Node name:",QLineEdit::Normal,current,&ok);if(!ok||name==current)return;amigaguide::Document d;if(!amigaguide::Parser{}.parse(editor_->toPlainText().toUtf8().toStdString(),d))return;amigaguide::DocumentEditor edit(d);std::string err;if(!edit.rename_node(static_cast<std::size_t>(row),name.toUtf8().toStdString(),&err)){QMessageBox::warning(this,"Cannot rename node",QString::fromStdString(err));return;}replaceSource(d.source(),row,"Renamed node to "+name);}
void MainWindow::deleteNode(){const int row=nodes_->currentRow();if(!applyNodeEdit("delete",row))return;const QString name=nodes_->currentItem()->text();if(QMessageBox::question(this,"Delete Node","Delete node \""+name+"\"? This removes its source block but does not rewrite links to it.",QMessageBox::Yes|QMessageBox::No)!=QMessageBox::Yes)return;amigaguide::Document d;if(!amigaguide::Parser{}.parse(editor_->toPlainText().toUtf8().toStdString(),d))return;amigaguide::DocumentEditor edit(d);std::string err;if(!edit.remove_node(static_cast<std::size_t>(row),&err)){QMessageBox::warning(this,"Cannot delete node",QString::fromStdString(err));return;}replaceSource(d.source(),std::max(0,row-1),"Deleted node "+name);}
void MainWindow::titleEdited(){if(updating_)return;const int row=nodes_->currentRow();if(!applyNodeEdit("change title",row))return;amigaguide::Document d;if(!amigaguide::Parser{}.parse(editor_->toPlainText().toUtf8().toStdString(),d))return;amigaguide::DocumentEditor edit(d);std::string err;if(!edit.set_node_title(static_cast<std::size_t>(row),titleEdit_->text().toUtf8().toStdString(),&err)){QMessageBox::warning(this,"Cannot change title",QString::fromStdString(err));return;}replaceSource(d.source(),row,"Updated node title");}
void MainWindow::propertyEdited(){if(updating_)return;const int row=nodes_->currentRow();if(row<0)return;auto* senderWidget=qobject_cast<QWidget*>(sender());if(!senderWidget)return;amigaguide::Document d;if(!amigaguide::Parser{}.parse(editor_->toPlainText().toUtf8().toStdString(),d))return;amigaguide::DocumentEditor edit(d);std::string err;std::string value;if(senderWidget==tabWidthEdit_)value=std::to_string(tabWidthEdit_->value());else value=qobject_cast<QLineEdit*>(senderWidget)->text().toUtf8().toStdString();if(!edit.set_node_property(static_cast<std::size_t>(row),propertyFor(senderWidget),value,&err)){QMessageBox::warning(this,"Cannot change property",QString::fromStdString(err));return;}replaceSource(d.source(),row,"Updated node property");}
void MainWindow::flagEdited(bool enabled){if(updating_)return;Q_UNUSED(enabled);const int row=nodes_->currentRow();if(row<0)return;auto* senderWidget=qobject_cast<QWidget*>(sender());amigaguide::Document d;if(!amigaguide::Parser{}.parse(editor_->toPlainText().toUtf8().toStdString(),d))return;amigaguide::DocumentEditor edit(d);std::string err;if(!edit.set_node_flag(static_cast<std::size_t>(row),flagFor(senderWidget),senderWidget->property("checked").toBool(),&err)){QMessageBox::warning(this,"Cannot change option",QString::fromStdString(err));return;}replaceSource(d.source(),row,"Updated node option");}

void MainWindow::documentProperties(){
    amigaguide::Document d;amigaguide::ParseError e;if(!amigaguide::Parser{}.parse(editor_->toPlainText().toUtf8().toStdString(),d,&e)){QMessageBox::warning(this,"Document Properties",QString("Fix the document's parse errors before editing properties.\nLine %1: %2").arg(e.line).arg(QString::fromStdString(e.message)));return;}
    QDialog dialog(this);dialog.setWindowTitle("Document Properties");dialog.resize(520,520);auto* layout=new QVBoxLayout(&dialog);auto* form=new QFormLayout;layout->addLayout(form);
    QLineEdit name(QString::fromStdString(d.metadata().name),&dialog),author(QString::fromStdString(d.metadata().author),&dialog),version(QString::fromStdString(d.metadata().version),&dialog),copyright(QString::fromStdString(d.metadata().copyright),&dialog),font(QString::fromStdString(d.metadata().font),&dialog),help(QString::fromStdString(d.metadata().help),&dialog),toc(QString::fromStdString(d.metadata().toc),&dialog),index(QString::fromStdString(d.metadata().index),&dialog),delimiter(QString::fromStdString(d.metadata().word_delimiter),&dialog);
    QSpinBox width(&dialog),height(&dialog),tab(&dialog);for(auto* s:{&width,&height,&tab}){s->setRange(0,10000);s->setSpecialValueText("Default");}width.setValue(d.metadata().width);height.setValue(d.metadata().height);tab.setValue(d.metadata().tab_width);
    QCheckBox wordWrap("Word wrap",&dialog),smartWrap("Smart wrap",&dialog);wordWrap.setChecked(d.metadata().word_wrap);smartWrap.setChecked(d.metadata().smart_wrap);
    form->addRow("Database",&name);form->addRow("Author",&author);form->addRow("Version",&version);form->addRow("Copyright",&copyright);form->addRow("Font",&font);form->addRow("Help",&help);form->addRow("TOC",&toc);form->addRow("Index",&index);form->addRow("Word delimiter",&delimiter);form->addRow("Width",&width);form->addRow("Height",&height);form->addRow("Tab width",&tab);form->addRow("Options",&wordWrap);form->addRow("",&smartWrap);
    auto* buttons=new QDialogButtonBox(QDialogButtonBox::Ok|QDialogButtonBox::Cancel,&dialog);layout->addWidget(buttons);connect(buttons,&QDialogButtonBox::accepted,&dialog,&QDialog::accept);connect(buttons,&QDialogButtonBox::rejected,&dialog,&QDialog::reject);if(dialog.exec()!=QDialog::Accepted)return;
    amigaguide::DocumentEditor edit(d);std::string err;auto set=[&](amigaguide::DocumentProperty p,const QString& v){return edit.set_document_property(p,v.toUtf8().toStdString(),&err);};
    if(!set(amigaguide::DocumentProperty::Name,name.text())||!set(amigaguide::DocumentProperty::Author,author.text())||!set(amigaguide::DocumentProperty::Version,version.text())||!set(amigaguide::DocumentProperty::Copyright,copyright.text())||!set(amigaguide::DocumentProperty::Font,font.text())||!set(amigaguide::DocumentProperty::Help,help.text())||!set(amigaguide::DocumentProperty::Toc,toc.text())||!set(amigaguide::DocumentProperty::Index,index.text())||!set(amigaguide::DocumentProperty::WordDelimiter,delimiter.text())||!set(amigaguide::DocumentProperty::Width,QString::number(width.value()))||!set(amigaguide::DocumentProperty::Height,QString::number(height.value()))||!set(amigaguide::DocumentProperty::TabWidth,QString::number(tab.value()))||!edit.set_document_flag(amigaguide::DocumentFlag::WordWrap,wordWrap.isChecked(),&err)||!edit.set_document_flag(amigaguide::DocumentFlag::SmartWrap,smartWrap.isChecked(),&err)){QMessageBox::warning(this,"Document Properties",QString::fromStdString(err));return;}
    replaceSource(d.source(),nodes_->currentRow(),"Updated document properties");
}

bool MainWindow::maybeSave(){if(!editor_->document()->isModified())return true;const auto answer=QMessageBox::warning(this,"Unsaved Changes","The current document has unsaved changes.",QMessageBox::Save|QMessageBox::Discard|QMessageBox::Cancel);if(answer==QMessageBox::Save){save();return !editor_->document()->isModified();}return answer==QMessageBox::Discard;}
