#include "mainwindow.h"
#include "editorui.h"
#include "amigaguide/document_editor.h"
#include "amigaguide/parser.h"

#include <algorithm>
#include <QCheckBox>
#include <QDialog>
#include <QDialogButtonBox>
#include <QFile>
#include <QFileDialog>
#include <QFileInfo>
#include <QFormLayout>
#include <QInputDialog>
#include <QLineEdit>
#include <QMessageBox>
#include <QPlainTextEdit>
#include <QSpinBox>
#include <QTextCursor>
#include <QVBoxLayout>

namespace {
amigaguide::NodeProperty propertyFor(QObject* o){const auto n=o->objectName();if(n=="keywords")return amigaguide::NodeProperty::Keywords;if(n=="prev")return amigaguide::NodeProperty::Prev;if(n=="next")return amigaguide::NodeProperty::Next;if(n=="help")return amigaguide::NodeProperty::Help;if(n=="toc")return amigaguide::NodeProperty::Toc;if(n=="index")return amigaguide::NodeProperty::Index;if(n=="font")return amigaguide::NodeProperty::Font;return amigaguide::NodeProperty::TabWidth;}
amigaguide::NodeFlag flagFor(QObject* o){const auto n=o->objectName();if(n=="smartwrap")return amigaguide::NodeFlag::SmartWrap;if(n=="proportional")return amigaguide::NodeFlag::Proportional;return amigaguide::NodeFlag::WordWrap;}
}

MainWindow::MainWindow(QWidget* parent)
    : QMainWindow(parent), ui_(std::make_unique<EditorUi>(this))
{
    ui_->setup();
    newFile();
}

MainWindow::~MainWindow() = default;

void MainWindow::newFile(){if(!maybeSave())return;updating_=true;ui_->editor->setPlainText("@database New AmigaGuide\n\n@node Main\n@title Main\n\n@endnode\n");updating_=false;filePath_.clear();setWindowTitle("AmigaGuide Editor — Untitled");updateNodes();ui_->editor->document()->setModified(false);}
void MainWindow::open(){const QString p=QFileDialog::getOpenFileName(this,"Open AmigaGuide",{},"AmigaGuide (*.guide *.amigaguide);;All files (*)");if(!p.isEmpty())openFile(p);}
void MainWindow::openFile(const QString& p){if(!maybeSave())return;QFile f(p);if(!f.open(QIODevice::ReadOnly|QIODevice::Text)){QMessageBox::warning(this,"Open failed","Could not open the selected AmigaGuide file.");return;}loadSource(QString::fromUtf8(f.readAll()));setDocumentPath(p);statusBar()->showMessage("Opened "+QFileInfo(p).fileName());}
void MainWindow::loadSource(const QString& s){updating_=true;ui_->editor->setPlainText(s);updating_=false;updateNodes();ui_->editor->document()->setModified(false);}
void MainWindow::save(){if(filePath_.isEmpty())saveAs();else saveTo(filePath_);}
void MainWindow::saveAs(){const QString p=QFileDialog::getSaveFileName(this,"Save AmigaGuide",filePath_.isEmpty()?"untitled.guide":filePath_,"AmigaGuide (*.guide);;All files (*)");if(!p.isEmpty())saveTo(p);}
bool MainWindow::saveTo(const QString& p){QFile f(p);if(!f.open(QIODevice::WriteOnly|QIODevice::Text)){QMessageBox::warning(this,"Save failed","Could not save the AmigaGuide file.");return false;}f.write(ui_->editor->toPlainText().toUtf8());setDocumentPath(p);ui_->editor->document()->setModified(false);statusBar()->showMessage("Saved "+QFileInfo(p).fileName());return true;}
void MainWindow::setDocumentPath(const QString& p){filePath_=p;setWindowTitle((QFileInfo(p).fileName().isEmpty()?"Untitled":QFileInfo(p).fileName())+" — AmigaGuide Editor");}
void MainWindow::updateNodes(){if(updating_)return;const QString selected=ui_->nodes->currentItem()?ui_->nodes->currentItem()->text():QString{};const int old=ui_->nodes->currentRow();const std::string source=ui_->editor->toPlainText().toUtf8().toStdString();amigaguide::Document d;amigaguide::ParseError e;if(!amigaguide::Parser{}.parse(source,d,&e)){ui_->nodes->clear();refreshProperties(-1);statusBar()->showMessage(QString("Parse error on line %1: %2").arg(e.line).arg(QString::fromStdString(e.message)));return;}updating_=true;ui_->nodes->clear();int row=-1;for(std::size_t i=0;i<d.nodes().size();++i){ui_->nodes->addItem(QString::fromStdString(d.nodes()[i].name));if(!selected.isEmpty()&&selected==QString::fromStdString(d.nodes()[i].name))row=static_cast<int>(i);}if(row<0&&old>=0&&old<ui_->nodes->count())row=old;if(row>=0)ui_->nodes->setCurrentRow(row);updating_=false;nodeActivated(ui_->nodes->currentRow());statusBar()->showMessage(QString("%1 node(s)").arg(d.nodes().size()));}
void MainWindow::nodeActivated(int row){if(row<0){refreshProperties(-1);return;}const std::string source=ui_->editor->toPlainText().toUtf8().toStdString();amigaguide::Document d;if(!amigaguide::Parser{}.parse(source,d)||row>=static_cast<int>(d.nodes().size()))return;refreshProperties(row);const auto& n=d.nodes()[static_cast<std::size_t>(row)];const qsizetype start=QString::fromUtf8(source.data(),static_cast<qsizetype>(n.source_begin)).size();const qsizetype end=QString::fromUtf8(source.data(),static_cast<qsizetype>(n.source_end)).size();QTextCursor c=ui_->editor->textCursor();c.setPosition(start);c.setPosition(end,QTextCursor::KeepAnchor);ui_->editor->setTextCursor(c);ui_->editor->centerCursor();}
void MainWindow::refreshProperties(int row){updating_=true;const std::string source=ui_->editor->toPlainText().toUtf8().toStdString();amigaguide::Document d;if(row>=0&&amigaguide::Parser{}.parse(source,d)&&row<static_cast<int>(d.nodes().size())){const auto& n=d.nodes()[static_cast<std::size_t>(row)];ui_->titleEdit->setText(QString::fromStdString(n.title));ui_->keywordsEdit->setText(QString::fromStdString(n.keywords));ui_->prevEdit->setText(QString::fromStdString(n.prev));ui_->nextEdit->setText(QString::fromStdString(n.next));ui_->helpEdit->setText(QString::fromStdString(n.help));ui_->tocEdit->setText(QString::fromStdString(n.toc));ui_->indexEdit->setText(QString::fromStdString(n.index));ui_->fontEdit->setText(QString::fromStdString(n.font));ui_->tabWidthEdit->setValue(n.tab_width);ui_->wordWrapEdit->setChecked(n.word_wrap);ui_->smartWrapEdit->setChecked(n.smart_wrap);ui_->proportionalEdit->setChecked(n.proportional);ui_->titleEdit->setEnabled(true);ui_->keywordsEdit->setEnabled(true);ui_->prevEdit->setEnabled(true);ui_->nextEdit->setEnabled(true);ui_->helpEdit->setEnabled(true);ui_->tocEdit->setEnabled(true);ui_->indexEdit->setEnabled(true);ui_->fontEdit->setEnabled(true);ui_->tabWidthEdit->setEnabled(true);ui_->wordWrapEdit->setEnabled(true);ui_->smartWrapEdit->setEnabled(true);ui_->proportionalEdit->setEnabled(true);}else{ui_->titleEdit->clear();ui_->keywordsEdit->clear();ui_->prevEdit->clear();ui_->nextEdit->clear();ui_->helpEdit->clear();ui_->tocEdit->clear();ui_->indexEdit->clear();ui_->fontEdit->clear();ui_->tabWidthEdit->setValue(0);ui_->wordWrapEdit->setChecked(false);ui_->smartWrapEdit->setChecked(false);ui_->proportionalEdit->setChecked(false);ui_->titleEdit->setEnabled(false);ui_->keywordsEdit->setEnabled(false);ui_->prevEdit->setEnabled(false);ui_->nextEdit->setEnabled(false);ui_->helpEdit->setEnabled(false);ui_->tocEdit->setEnabled(false);ui_->indexEdit->setEnabled(false);ui_->fontEdit->setEnabled(false);ui_->tabWidthEdit->setEnabled(false);ui_->wordWrapEdit->setEnabled(false);ui_->smartWrapEdit->setEnabled(false);ui_->proportionalEdit->setEnabled(false);}updating_=false;}
void MainWindow::setNodeSelection(int row){if(row>=0&&row<ui_->nodes->count())ui_->nodes->setCurrentRow(row);}
bool MainWindow::applyNodeEdit(const QString& op,int row){const std::string s=ui_->editor->toPlainText().toUtf8().toStdString();amigaguide::Document d;amigaguide::ParseError e;if(!amigaguide::Parser{}.parse(s,d,&e)){QMessageBox::warning(this,"Cannot edit node",QString("The document must parse before a node can be %1.").arg(op));return false;}return row>=0&&row<static_cast<int>(d.nodes().size());}
void MainWindow::replaceSource(const std::string& s,int row,const QString& msg){updating_=true;ui_->editor->setPlainText(QString::fromUtf8(s.data(),static_cast<qsizetype>(s.size())));updating_=false;ui_->editor->document()->setModified(true);updateNodes();setNodeSelection(row);statusBar()->showMessage(msg);}
void MainWindow::newNode(){bool ok=false;const QString name=QInputDialog::getText(this,"New Node","Node name:",QLineEdit::Normal,"NewNode",&ok);if(!ok)return;const QString title=QInputDialog::getText(this,"New Node","Node title:",QLineEdit::Normal,name,&ok);if(!ok)return;amigaguide::Document d;amigaguide::ParseError e;if(!amigaguide::Parser{}.parse(ui_->editor->toPlainText().toUtf8().toStdString(),d,&e)){QMessageBox::warning(this,"Cannot add node","Fix the document's parse errors before adding a node.");return;}amigaguide::DocumentEditor edit(d);std::string err;if(!edit.add_node(name.toUtf8().toStdString(),title.toUtf8().toStdString(),&err)){QMessageBox::warning(this,"Cannot add node",QString::fromStdString(err));return;}replaceSource(d.source(),static_cast<int>(d.nodes().size())-1,"Added node "+name);}
void MainWindow::renameNode(){const int row=ui_->nodes->currentRow();if(!applyNodeEdit("rename",row))return;const QString current=ui_->nodes->currentItem()->text();bool ok=false;const QString name=QInputDialog::getText(this,"Rename Node","Node name:",QLineEdit::Normal,current,&ok);if(!ok||name==current)return;amigaguide::Document d;if(!amigaguide::Parser{}.parse(ui_->editor->toPlainText().toUtf8().toStdString(),d))return;amigaguide::DocumentEditor edit(d);std::string err;if(!edit.rename_node(static_cast<std::size_t>(row),name.toUtf8().toStdString(),&err)){QMessageBox::warning(this,"Cannot rename node",QString::fromStdString(err));return;}replaceSource(d.source(),row,"Renamed node to "+name);}
void MainWindow::deleteNode(){const int row=ui_->nodes->currentRow();if(!applyNodeEdit("delete",row))return;const QString name=ui_->nodes->currentItem()->text();if(QMessageBox::question(this,"Delete Node","Delete node \""+name+"\"? This removes its source block but does not rewrite links to it.",QMessageBox::Yes|QMessageBox::No)!=QMessageBox::Yes)return;amigaguide::Document d;if(!amigaguide::Parser{}.parse(ui_->editor->toPlainText().toUtf8().toStdString(),d))return;amigaguide::DocumentEditor edit(d);std::string err;if(!edit.remove_node(static_cast<std::size_t>(row),&err)){QMessageBox::warning(this,"Cannot delete node",QString::fromStdString(err));return;}replaceSource(d.source(),std::max(0,row-1),"Deleted node "+name);}
void MainWindow::titleEdited(){if(updating_)return;const int row=ui_->nodes->currentRow();if(!applyNodeEdit("change title",row))return;amigaguide::Document d;if(!amigaguide::Parser{}.parse(ui_->editor->toPlainText().toUtf8().toStdString(),d))return;amigaguide::DocumentEditor edit(d);std::string err;if(!edit.set_node_title(static_cast<std::size_t>(row),ui_->titleEdit->text().toUtf8().toStdString(),&err)){QMessageBox::warning(this,"Cannot change title",QString::fromStdString(err));return;}replaceSource(d.source(),row,"Updated node title");}
void MainWindow::propertyEdited(){if(updating_)return;const int row=ui_->nodes->currentRow();if(row<0)return;auto* senderWidget=qobject_cast<QWidget*>(sender());if(!senderWidget)return;amigaguide::Document d;if(!amigaguide::Parser{}.parse(ui_->editor->toPlainText().toUtf8().toStdString(),d))return;amigaguide::DocumentEditor edit(d);std::string err;std::string value;if(senderWidget==ui_->tabWidthEdit)value=std::to_string(ui_->tabWidthEdit->value());else value=qobject_cast<QLineEdit*>(senderWidget)->text().toUtf8().toStdString();if(!edit.set_node_property(static_cast<std::size_t>(row),propertyFor(senderWidget),value,&err)){QMessageBox::warning(this,"Cannot change property",QString::fromStdString(err));return;}replaceSource(d.source(),row,"Updated node property");}
void MainWindow::flagEdited(bool enabled){if(updating_)return;Q_UNUSED(enabled);const int row=ui_->nodes->currentRow();if(row<0)return;auto* senderWidget=qobject_cast<QWidget*>(sender());amigaguide::Document d;if(!amigaguide::Parser{}.parse(ui_->editor->toPlainText().toUtf8().toStdString(),d))return;amigaguide::DocumentEditor edit(d);std::string err;if(!edit.set_node_flag(static_cast<std::size_t>(row),flagFor(senderWidget),senderWidget->property("checked").toBool(),&err)){QMessageBox::warning(this,"Cannot change option",QString::fromStdString(err));return;}replaceSource(d.source(),row,"Updated node option");}

void MainWindow::documentProperties(){
    amigaguide::Document d;amigaguide::ParseError e;if(!amigaguide::Parser{}.parse(ui_->editor->toPlainText().toUtf8().toStdString(),d,&e)){QMessageBox::warning(this,"Document Properties",QString("Fix the document's parse errors before editing properties.\nLine %1: %2").arg(e.line).arg(QString::fromStdString(e.message)));return;}
    QDialog dialog(this);dialog.setWindowTitle("Document Properties");dialog.resize(520,520);auto* layout=new QVBoxLayout(&dialog);auto* form=new QFormLayout;layout->addLayout(form);
    QLineEdit name(QString::fromStdString(d.metadata().name),&dialog),author(QString::fromStdString(d.metadata().author),&dialog),version(QString::fromStdString(d.metadata().version),&dialog),copyright(QString::fromStdString(d.metadata().copyright),&dialog),font(QString::fromStdString(d.metadata().font),&dialog),help(QString::fromStdString(d.metadata().help),&dialog),toc(QString::fromStdString(d.metadata().toc),&dialog),index(QString::fromStdString(d.metadata().index),&dialog),delimiter(QString::fromStdString(d.metadata().word_delimiter),&dialog);
    QSpinBox width(&dialog),height(&dialog),tab(&dialog);for(auto* s:{&width,&height,&tab}){s->setRange(0,10000);s->setSpecialValueText("Default");}width.setValue(d.metadata().width);height.setValue(d.metadata().height);tab.setValue(d.metadata().tab_width);
    QCheckBox wordWrap("Word wrap",&dialog),smartWrap("Smart wrap",&dialog);wordWrap.setChecked(d.metadata().word_wrap);smartWrap.setChecked(d.metadata().smart_wrap);
    form->addRow("Database",&name);form->addRow("Author",&author);form->addRow("Version",&version);form->addRow("Copyright",&copyright);form->addRow("Font",&font);form->addRow("Help",&help);form->addRow("TOC",&toc);form->addRow("Index",&index);form->addRow("Word delimiter",&delimiter);form->addRow("Width",&width);form->addRow("Height",&height);form->addRow("Tab width",&tab);form->addRow("Options",&wordWrap);form->addRow("",&smartWrap);
    auto* buttons=new QDialogButtonBox(QDialogButtonBox::Ok|QDialogButtonBox::Cancel,&dialog);layout->addWidget(buttons);connect(buttons,&QDialogButtonBox::accepted,&dialog,&QDialog::accept);connect(buttons,&QDialogButtonBox::rejected,&dialog,&QDialog::reject);if(dialog.exec()!=QDialog::Accepted)return;
    amigaguide::DocumentEditor edit(d);std::string err;auto set=[&](amigaguide::DocumentProperty p,const QString& v){return edit.set_document_property(p,v.toUtf8().toStdString(),&err);};
    if(!set(amigaguide::DocumentProperty::Name,name.text())||!set(amigaguide::DocumentProperty::Author,author.text())||!set(amigaguide::DocumentProperty::Version,version.text())||!set(amigaguide::DocumentProperty::Copyright,copyright.text())||!set(amigaguide::DocumentProperty::Font,font.text())||!set(amigaguide::DocumentProperty::Help,help.text())||!set(amigaguide::DocumentProperty::Toc,toc.text())||!set(amigaguide::DocumentProperty::Index,index.text())||!set(amigaguide::DocumentProperty::WordDelimiter,delimiter.text())||!set(amigaguide::DocumentProperty::Width,QString::number(width.value()))||!set(amigaguide::DocumentProperty::Height,QString::number(height.value()))||!set(amigaguide::DocumentProperty::TabWidth,QString::number(tab.value()))||!edit.set_document_flag(amigaguide::DocumentFlag::WordWrap,wordWrap.isChecked(),&err)||!edit.set_document_flag(amigaguide::DocumentFlag::SmartWrap,smartWrap.isChecked(),&err)){QMessageBox::warning(this,"Document Properties",QString::fromStdString(err));return;}
    replaceSource(d.source(),ui_->nodes->currentRow(),"Updated document properties");
}

bool MainWindow::maybeSave(){if(!ui_->editor->document()->isModified())return true;const auto answer=QMessageBox::warning(this,"Unsaved Changes","The current document has unsaved changes.",QMessageBox::Save|QMessageBox::Discard|QMessageBox::Cancel);if(answer==QMessageBox::Save){save();return !ui_->editor->document()->isModified();}return answer==QMessageBox::Discard;}
