#include "amigaguide/renderer.h"

#include <algorithm>
#include <cctype>
#include <sstream>
#include <string>
#include <string_view>

namespace amigaguide {
namespace {
std::string html_escape(std::string_view s){std::string o; for(char c:s){switch(c){case '&':o+="&amp;";break;case '<':o+="&lt;";break;case '>':o+="&gt;";break;case '"':o+="&quot;";break;default:o+=c;}} return o;}
std::string lower(std::string_view s){std::string o(s);std::transform(o.begin(),o.end(),o.begin(),[](unsigned char c){return static_cast<char>(std::tolower(c));});return o;}
std::string trim(std::string_view s){std::size_t a=0,b=s.size();while(a<b&&std::isspace(static_cast<unsigned char>(s[a])))++a;while(b>a&&std::isspace(static_cast<unsigned char>(s[b-1])))--b;return std::string(s.substr(a,b-a));}
std::string first_token(std::string_view s){while(!s.empty()&&std::isspace(static_cast<unsigned char>(s.front())))s.remove_prefix(1);auto p=s.find_first_of(" \t\r\n");return std::string(s.substr(0,p));}
bool quoted(std::string_view s,std::string& value,std::size_t& end){if(s.empty()||s.front()!='"')return false;std::string r;bool esc=false;for(std::size_t i=1;i<s.size();++i){char c=s[i];if(esc){r+=c;esc=false;continue;}if(c=='\\'){esc=true;continue;}if(c=='"'){value=r;end=i+1;return true;}r+=c;}return false;}
std::string css_color(std::string_view v){auto c=lower(trim(v));if(c=="black"||c=="white"||c=="red"||c=="green"||c=="blue"||c=="yellow"||c=="cyan"||c=="magenta"||c=="gray"||c=="grey"||c=="orange"||c=="purple")return c;return {};}
struct Style{bool bold=false,italic=false,underline=false;std::string fg,bg,align="left";int indent=0;};
std::string style_css(const Style&s){std::ostringstream c;if(s.bold)c<<"font-weight:bold;";if(s.italic)c<<"font-style:italic;";if(s.underline)c<<"text-decoration:underline;";if(!s.fg.empty())c<<"color:"<<s.fg<<';';if(!s.bg.empty())c<<"background-color:"<<s.bg<<';';if(s.indent)c<<"margin-left:"<<s.indent*1.5<<"em;";if(s.align!="left")c<<"text-align:"<<s.align<<';';return c.str();}
void append_span(std::string&o,const Style&s,std::string_view t){if(t.empty())return;auto css=style_css(s);if(css.empty())o+=html_escape(t);else o+="<span style=\""+css+"\">"+html_escape(t)+"</span>";}
std::string node_body(const Document&d,const Node&n){const auto&s=d.source();if(n.source_begin>=s.size())return{};auto b=s.find('\n',n.source_begin);if(b==std::string::npos)return{};++b;auto e=n.source_end;e=std::min(e,s.size());auto m=s.rfind("@endnode",e);if(m!=std::string::npos&&m>=b)e=m;return s.substr(b,e-b);}
std::string render_text(std::string_view text){std::string out,pending;Style style;auto flush=[&]{append_span(out,style,pending);pending.clear();};for(std::size_t i=0;i<text.size();){if(text[i]=='\\'&&i+1<text.size()&&(text[i+1]=='@'||text[i+1]=='\\')){pending+=text[i+1];i+=2;continue;}if(text[i]!='@'||i+1>=text.size()||text[i+1]!='{'){pending+=text[i++];continue;}auto close=text.find('}',i+2);if(close==std::string_view::npos){pending+=text[i++];continue;}auto raw=trim(text.substr(i+2,close-i-2));auto cmd=lower(first_token(raw));flush();
if(cmd=="b")style.bold=true;else if(cmd=="ub")style.bold=false;else if(cmd=="i")style.italic=true;else if(cmd=="ui")style.italic=false;else if(cmd=="u")style.underline=true;else if(cmd=="uu")style.underline=false;else if(cmd=="jleft")style.align="left";else if(cmd=="jcenter")style.align="center";else if(cmd=="jright")style.align="right";else if(cmd=="lindent"){try{style.indent=std::max(0,std::stoi(first_token(std::string_view(raw).substr(cmd.size()))));}catch(...){style.indent=0;}}else if(cmd=="fg")style.fg=css_color(std::string_view(raw).substr(cmd.size()));else if(cmd=="bg")style.bg=css_color(std::string_view(raw).substr(cmd.size()));else if(cmd=="par")out+="<br><br>";else if(cmd=="line")out+="<br>";else if(cmd=="tab")out+="&nbsp;&nbsp;&nbsp;&nbsp;";else if(!raw.empty()&&raw.front()=='"'){std::string label;std::size_t used=0;if(quoted(raw,label,used)){auto rest=trim(std::string_view(raw).substr(used));auto action=lower(first_token(rest));if(action=="link"){rest=trim(std::string_view(rest).substr(4));std::string target;std::size_t u=0;if(quoted(rest,target,u)||!(target=first_token(rest)).empty())out+="<a href=\"node:"+html_escape(target)+"\">"+html_escape(label)+"</a>";else pending+=label;}else pending+=label;}else pending+="@{"+raw+"}";}else pending+="@{"+raw+"}";i=close+1;}flush();return out;}
}
std::string render_node_html(const Document&document,const Node&node){auto body=node_body(document,node);std::string html="<div class=\"guide-node\"><h1>"+html_escape(node.title.empty()?node.name:node.title)+"</h1><div class=\"guide-body\">";std::size_t pos=0;while(pos<body.size()){auto nl=body.find('\n',pos);auto e=nl==std::string::npos?body.size():nl;std::string_view line(body.data()+pos,e-pos);auto t=trim(line);if(!t.empty()&&t.front()=='@'){auto cmd=lower(first_token(std::string_view(t).substr(1)));if(cmd=="next"||cmd=="prev"||cmd=="help"||cmd=="toc"||cmd=="index"||cmd=="keywords"||cmd=="font"||cmd=="width"||cmd=="height"||cmd=="tab"||cmd=="wordwrap"||cmd=="smartwrap"||cmd=="endnode"){pos=nl==std::string::npos?body.size():nl+1;continue;}}if(line.empty())html+="<br>";else html+=render_text(line)+"<br>";pos=nl==std::string::npos?body.size():nl+1;}html+="</div></div>";return html;}
} // namespace amigaguide
